project:
  type: website

website:
  title: "Adam Taheraly"
  description: "Research, projects, and writing"
  site-url: "https://adamtaheraly.github.io"
  favicon: favicon.ico

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About / CV
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/adamtaheraly
      - icon: linkedin
        href: https://linkedin.com/in/adam-taheraly
      - icon: researchgate
        href: https://www.researchgate.net/profile/Adam-Taheraly
      - icon: orcid
        href: https://orcid.org/0000-0002-7818-9064

format:
  html:
    theme: lumen
    css: styles.css
    toc: true



